### ISSUE TITLE
Page Preview Not Working

### ISSUE THREAD

**Issue by stpaultim** [backdrop-contrib/paragraphs#136] opened 2022-06-17 07:26 UTC
I've just noticed that the node edit PREVIEW button does not seem to be working with my paragraphs. 

Is this is known limitation of Paragraphs (if so, is it documented anywhere for folks like me to find) or is this a bug?

Or am I just doing something wrong.

![image](https://user-images.githubusercontent.com/3144571/174247585-eb051fe2-882c-4281-b046-b7d7ce7bd7c3.png)

**Comment by argiepiano** [comment] 2022-06-17 13:55
Can you describe "not working" in more detail please? How to reproduce?

**Comment by sudipto68** [comment] 2022-06-27 11:58
We are using different paragraph types for our content and they work perfectly when we Save and View the page but if we try the Preview button there seen nothing on that Preview page. In Simple, Paragraphs are not working on the Preview page.

**Comment by stpaultim** [comment] 2022-06-29 04:22
As @sudipto68 reported. If I click on the preview I see the page title and the blocks that appear below the page content, but the page content is not visible at all - there is no preview of the content contained within the paragraphs on that page.

**Comment by argiepiano** [comment] 2022-06-30 04:51
@laryn and @stpaultim, I've done a bit of debugging on why the Preview button doesn't show the Paragraph fields in a node.

So, in Backdrop, Paragraphs implements  hook_field_prepare_view() (in file paragraphs.field_formatter.inc). I don't know what the purpose of this implementation is, but I suspect it's related to the experimental modal administration. The issue is that, in that hook, the function assigns a value of 'scratch_paragraph` to the Paragraph item, I think ONLY when you are in editing mode (once the node is saved, the value is actually the paragraph item ID). 

So, `paragraphs_field_formatter_view()`, which produces the output, finds that flag `scratch_paragraph` and effectively skips rendering the field. Again, this only happens while editing and pressing Preview.

I commented out `hook_field_prepare_view()` and slightly modified `paragraphs_field_formatter_view()` and the Preview works, BUT I haven't tried the rest of the functionality  - this may mess up the modal admin etc.

I'm not a maintainer of this module and don't quite have the time to thoroughly test, but I thought I mentioned what I've found in case someone wants to fix this.

**Comment by argiepiano** [comment] 2022-06-30 04:55
Also tried leaving hook_field_prepare_view() as is, and commenting out lines 101-107 in paragraphs_field_formatter_view()  and that also works for the Preview...

**Comment by stpaultim** [comment] 2022-06-30 06:53
@argiepiano Thanks. I'm not sure that I'll be able to fix this. But, maybe I can recruit someone who can.

**Comment by argiepiano** [comment] 2022-06-30 14:11
A couple more thoughts: `scratch_paragraph` is used to avoid rendering the Paragraph field. @laryn added this is #60 not too long ago. And as I suspected it was added when the modal editing was added. It's unclear to me what @laryn was trying to solve with this.

I have tested by removing BOTH `paragraphs_field_prepare_view()` AND lines 101-107 (see below), and the modal still works fine in my testing, and the Preview starts working now.

So the key is to figure out if there is any situation when avoiding the rendering of the field, and `scratch_paragraph` flag are really needed. My guess is that @laryn put it there because he adapted an [unmerged D7 change](https://www.drupal.org/files/issues/interdiff-2448677-20-24.txt) that used it. The difference with that is that, that D7 patch did not use a modal, so my guess is that avoiding rendering the Paragraphs field was somehow needed in that situation.

This is what I removed in `paragraphs_field_formatter_view()` (in addition to the whole `paragraphs_field_prepare_view()` function).

```php

      // If we are dealing with an empty paragraphs field, render an insert point.
      if ($items[0]['value'] == 'scratch_paragraph') {
        if (!empty($instance['settings']['modal_admin'])) {
          $entity_ids = entity_extract_ids($entity_type, $entity);
        }
        return $element;
      }
```

**Comment by argiepiano** [comment] 2022-06-30 14:18
Just wanted to add that this has to be looked at carefully. I haven't tested in all situations, e.g. nested paragraphs...

**Comment by laryn** [comment] 2022-08-26 21:13
@argiepiano Thanks for digging into this as much as you have. If memory serves, the `scratch_paragraph` was intended for front end administration in the case that we have a paragraphs field that is empty, so that we can still add the front end admin options to create a new paragraphs item from the front end. But it's worth testing to make sure it's actually doing that, or needed. You are right that the D7 patch formed the basis for this experimental feature and I'm sure there are still some bugs to be worked out.

@stpaultim I'm not sure when I'll be able to get to this so feel free to recruit someone before then if you are able.

**Comment by sudipto68** [comment] 2022-09-29 11:30
@argiepiano  and @laryn thanks for figuring out this issue. We tested commenting out both the `paragraphs_field_prepare_view()` and  lines 101-107 in `paragraphs.field_formatter.inc` and found preview shows all paragraphs except paragraphs which using paragraphs jquery ui accordion (I guess thats another issue). Nested paragraphs were showing perfectly. But we got some notice as below - 
![It is a test update _ Friends of the Mississippi River](https://user-images.githubusercontent.com/53519888/193020339-947a0834-cb16-4ab5-9fa9-03a1e95315c1.png)

**Comment by sudipto68** [comment] 2022-10-13 12:11
I have submitted a PR Based on the solution. Here is the PR [136](https://github.com/backdrop-contrib/paragraphs/pull/146)

**Comment by herbdool** [comment] 2024-07-30 21:43
I must admit that I don't know if/how the modal admin works (which was part of https://www.drupal.org/files/issues/interdiff-2448677-20-24.txt which was merged). But I can see that the section in `paragraphs_field_formatter_view()` mentioned above is missing the line: `$element[0]['insert_point'] = paragraphs_create_insert_point($entity_type, $entity_ids[0], 'scratch', $instance['field_name']);` which calls a function which adds a contextual link. So maybe modal admin isn't working for me - no contextual link? And it returns an empty array.

At any rate, I have also removed it in testing. But I've also changed `paragraphs_field_prepare_view()` to this:

```
function paragraphs_field_prepare_view($entity_type, $entities, $field, $instances, $langcode, &$items) {
  if ($field['type'] == 'paragraphs') {
    foreach ($items as $key => $item) {
      foreach ($item as $delta => $instance) {
        if (!isset($instance['value'])) {
          $items[$key][$delta]['value'] = 'scratch_paragraph';
        }
      }
    }
  }
}
```

Because the node preview seems to ignore paragraphs nested in paragraphs but adding `scratch_paragraph` prevents it from dropping. But as it is currently it only adds `scratch_paragraph` to the first item. My change adds it to each item.

This is just a temporary fix though since the preview still doesn't seem to behave the same as a regular render - the preprocess functions are not running properly, somehow, that were required for some paragraphs types I've got in testing.

**Comment by herbdool** [comment] 2024-08-05 20:08
I've now updated the PR to also prevent the `modal_admin` links from appearing if in node preview. (We want to prevent them from appearing because it breaks the way a preview should work - the user shouldn't be able to edit and save the content while still in preview.)

I've separately figured out the issue I had with modal_admin appearing. It now seems to be fully working for me.

@laryn @olafgrabienski would you like to take a look at the PR? Node preview should work with complex paragraphs types (such as in `paragraphs_aplenty`) and the modal admin links should *not* appear on preview.

**Comment by olafgrabienski** [comment] 2024-08-11 10:49
@herbdool, I can probably have a look by end of the week.

**Comment by olafgrabienski** [comment] 2024-08-15 17:01
@herbdool I've had a look at the updated PR. As far as I can see, the node preview works with Paragraphs (even complex types, e.g. Accordion, Cards, Media List). The modal admin links do not appear (as expected).

In DBlog, I see however two warnings after editing and/or saving content with a Paragraphs field:

- Undefined array key 0 in file_field_widget_form() (line 712 of core/modules/file/file.field.inc).
- Trying to access array offset on value of type null in file_field_widget_form() (line 712 of core/modules/file/file.field.inc).

**Comment by laryn** [comment] 2024-08-16 03:38
Sounds like we're close here with just a few rough edges turned up by @olafgrabienski -- thanks for your work on this @herbdool and @olafgrabienski! I can do a round of testing after @herbdool sees and responds to the latest findings.

**Comment by herbdool** [comment] 2024-08-16 03:56
@olafgrabienski do you see the same errors without the patch?

**Comment by olafgrabienski** [comment] 2024-08-16 06:47
> do you see the same errors without the patch?

Yes, I do. (Sorry for not checking before.) No idea about the reason, though. There are some contrib modules on the test site, but not many:
- backup_migrate                     1.x-1.0.26
- colorbox                           1.x-2.17.2
- entity_plus                        1.x-1.0.21
- expanding_formatter                1.x-1.0.0
- html5_upload                       1.x-1.1.3
- paragraphs                         1.x-1.3.0
- paragraphs_aplenty                 1.x-1.2.1
- paragraphs_aplenty_gallery         1.x-1.2.1
- paragraphs_bundle_permissions      1.x-1.3.0

**Comment by herbdool** [comment] 2024-08-16 14:34
@laryn sounds like those errors are not due to this PR.

**Comment by laryn** [comment] 2024-08-16 21:35
@herbdool Okay, I'll try to review this soon.
@olafgrabienski If you can reproduce those errors, can you open in a separate issue?

**Closed as completed** 2024-08-30 19:34 UTC
