### ISSUE TITLE
Scheduling a node for publication in the future fails if it has a paragraph field on it.

### ISSUE THREAD

**Issue by serundeputy** [backdrop-contrib/paragraphs#54] opened 2020-03-21 16:24 UTC
When scheduling a node w/ a paragraphs field to be published in the future it fails:

```bash
gff ~/code/aturnintime/htb (master) 
└─ $ ∴ lando.dev drush cron
Error: Call to undefined function entity_revision_load() in paragraphs_item_revision_load() (line 60 of /app/web/modules/contrib/paragraphs/paragraphs.module).
Drush command terminated abnormally due to an unrecoverable error.                                                                                                                                                                                   [error]
```

The function entity_revision_load was provided by the entity module in D7. In Backdrop the function is in entity_plus and therefore is namespaced as entity_plus_revision_load.

**Comment by serundeputy** [comment] 2020-03-21 16:26
I went to file a PR for this, but it is already fixed in `1.x-1.x` https://github.com/backdrop-contrib/paragraphs/blob/1.x-1.x/paragraphs.module#L61, however the fix is not in the latest release `1.x-1.0.1`

Making a new release would fix this issue for me.

**Comment by laryn** [comment] 2020-03-31 19:58
Thanks @serundeputy -- I'm going to mark as a duplicate of https://github.com/backdrop-contrib/paragraphs/issues/33

As you noted this should be fixed in the `1.x-1.x` and I'm hoping to make a new release soon. Just hoping for another kick or two of the tires from users.

**Closed as completed by laryn** 2020-03-31 19:58 UTC
